### ISSUE TITLE
Upgrade Spark version to 1.1.1

### ISSUE THREAD

**Issue by ajnavarro** [Stratio/streaming-cep-engine#16]

**Comment by bhack** [comment]
I think 1.3 now.

**Comment by dmorales-stratio** [comment]
Agree.

Anyway, we have not already upgraded because of an issue about working with several contexts in the same JVM.

Maybe this comment is the best way to understand our problem: 

https://issues.apache.org/jira/browse/SPARK-4133?focusedCommentId=14196455&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14196455

We should try 1.3 anyway.

**Comment by bhack** [comment]
@dmorales-stratio https://issues.apache.org/jira/browse/SPARK-2243:
>SparkContext constructor will throw an exception in 1.3 if you try to instantiate a second one. You can turn it off with spark.driver.allowMultipleContexts=true

**Comment by mariomgal** [comment]
Spark version has been upgraded to 1.3.1. The property for allowing multiple context doesn't work properly, and it is also discouraged out of test environments. We have finally unified the three used Spark contexts into only one.
