### ISSUE TITLE
Handling non occurrences

### ISSUE THREAD

**Issue by bhack** [Stratio/streaming-cep-engine#24]
Is there a workaround  to handle [non occurrences](http://stackoverflow.com/questions/25555714/using-siddhi-patterns-for-events-that-havent-happened) on sequences and patterns?j

**Comment by dmorales-stratio** [comment]
Not at this moment, since we rely all CEP queries on Siddhi.

We have some workarounds to be noticed when a stream is not receiving
events in a period of time (based on queries), but not for non occurrences
on sequences and patterns.

We expect this feature in the next Siddhi release.

Thanks

2015-03-31 20:20 GMT+02:00 bhack <notifications@github.com>:

> Is there a workaround to handle non occurrences
> <http://stackoverflow.com/questions/25555714/using-siddhi-patterns-for-events-that-havent-happened>
> on sequences and patterns?j
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stratio/streaming-cep-engine/issues/24>.
>



-- 

David Morales de Frías  ::  +34 607 010 411 :: @dmoralesdf
<https://twitter.com/dmoralesdf>


<http://www.stratio.com/>
Vía de las dos Castillas, 33, Ática 4, 3ª Planta
28224 Pozuelo de Alarcón, Madrid
Tel: +34 91 828 6473 // www.stratio.com // *@stratiobd
<https://twitter.com/StratioBD>*

**Comment by bhack** [comment]
Why you are not aligned with siddhi 3.1.0? With event table something more is possible. But with 2.0 it is quite hard to implement something.

**Comment by dmorales-stratio** [comment]
We should definitely consider the upgrade. Feel free to create an issue and
we will take care of it ASAP.


2015-04-01 11:43 GMT+02:00 bhack <notifications@github.com>:

> Why you are not aligned with siddhi 3.1.0? With event table something more
> is possible. But with 2.0 it is quite hard to implement something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Stratio/streaming-cep-engine/issues/24#issuecomment-88416483>
> .
>



-- 

David Morales de Frías  ::  +34 607 010 411 :: @dmoralesdf
<https://twitter.com/dmoralesdf>


<http://www.stratio.com/>
Vía de las dos Castillas, 33, Ática 4, 3ª Planta
28224 Pozuelo de Alarcón, Madrid
Tel: +34 91 828 6473 // www.stratio.com // *@stratiobd
<https://twitter.com/StratioBD>*

**Comment by bhack** [comment]
Thank you I've opened a new one.
